### ISSUE TITLE
get infographic to play nice w/ site

### ISSUE THREAD

**Issue by bbest** [marinebon/fk-esr-info#11]
For now, we've been getting the infographic to work in:

* [infographic_r.html](https://marinebon.org/fk-esr-info/infographic_r.html)
  ![image](https://user-images.githubusercontent.com/2837257/109683026-ceeb2e80-7b33-11eb-834f-4b3972fecc1c.png)

but need to get it to work with existing site (and associated CSS, JS, etc) here:

* [infographic.html](https://marinebon.org/fk-esr-info/infographic_r.html)
  ![image](https://user-images.githubusercontent.com/2837257/109683097-e1656800-7b33-11eb-912c-6c806261f03d.png)

And along the way, handle:

* bulleted list indenting and margins so SVG fits neatly next to table of contents (TOC)

**Comment by bbest** [comment]
I don't see Bootstrap in the source:

* [view-source:https://marinebon.org/fk-esr-info/home.html](view-source:https://marinebon.org/fk-esr-info/home.html)
  * [https://marinebon.org/fk-esr-info/assets/css/main.css](https://marinebon.org/fk-esr-info/assets/css/main.css)
    * [HTML5 UP! Responsive HTML5 and CSS3 Site Templates](https://html5up.net/)
      * [Spectral | HTML5 UP](https://html5up.net/spectral)

Instead, we could try adding some CSS to overwrite infographic specific HTML tags. Here's a little tutorial:

* [Website Tutorial with HTML5 UP template](https://astrosites.github.io/tutorial/)

**Comment by superjai** [comment]
Hey @bbest - progress of a sort. At least I have identified the problem with the tooltip not showing up on the illustration. Careful checking at the console log indicated that your code is putting the tooltip together okay - it just isn't being displayed over the image properly for some reason.

I have created a [test file](https://github.com/marinebon/fk-esr-info/blob/main/example.html) to illustrate the problem. Here the only icon that works (or "works") is the mangroves one. You'll see when you mouse over the mangroves, the tooltip is below the image. 

![Screen Shot 2021-03-05 at 9 47 05 AM](https://user-images.githubusercontent.com/1744300/110153409-ddd21b00-7d97-11eb-88d4-4d5f74d99b8d.png)

**Comment by bbest** [comment]
Fundamentally, the working layout in [infographic_r.html](https://marinebon.org/fk-esr-info/infographic_r.html) allocates 9/12 (`col-md-9`) to the SVG illustration and 3/12 (`col-md-3`) to the table of contents (toc) list because vanilla Rmarkdown includes Bootstrap 3 having a "grid system that appropriately scales up to 12 columns":

```html
<div class="col-md-9">
 <div id="svg">
 </div>
 </div>
 <div class="col-md-3">
 <ul id="svg_list" style="list-style-type: none;">
 </ul>
</div>
```

In contrast, [infographic.html](https://marinebon.org/fk-esr-info/infographic.html) does NOT include Bootstrap, so the "grid" classes (`col-md-9`, `col-md-3`) don't get applied. I am still rather baffled as to what CSS gets included in [HTML5 UP! Responsive HTML5 and CSS3 Site Templates](https://html5up.net/).

## CSS/HTML Resources 

From [Hadley Wickham on Twitter: "What short tutorial would you recommend to an R user who wanted to learn the basics of HTML and CSS?" / Twitter](https://twitter.com/hadleywickham/status/1367103439474462726):

* [HTML & CSS Is Hard | A friendly web development tutorial](https://www.internetingishard.com/html-and-css/)
* [Traversy Media - YouTube](https://www.youtube.com/channel/UC29ju8bIPH5as8OGnQzwJyA)
* [CSS Diner - Where we feast on CSS Selectors!](https://flukeout.github.io/)
* [Flexbox Froggy - A game for learning CSS flexbox](https://flexboxfroggy.com/)
* [Learn to Code — For Free — Coding Courses for Busy People](https://www.freecodecamp.org/)
* [Kevin Powell - YouTube](https://www.youtube.com/kepowob/videos)
* [Dev Ed - YouTube](https://www.youtube.com/c/DevEd/videos)

**Comment by bbest** [comment]
Next steps:
1. Get the simpler **footer**, eg on [human-activities.html](https://marinebon.org/fk-esr-info/human-activities.html), working within [infographic.html](https://marinebon.org/fk-esr-info/infographic.html):
![image](https://user-images.githubusercontent.com/2837257/110551912-477d5c80-80eb-11eb-8104-73e4e8594b14.png)
2. Get the simplest **header**, eg just gray bar nav menu (and NOT banner image) from on [human-activities.html](https://marinebon.org/fk-esr-info/human-activities.html), working within [infographic.html](https://marinebon.org/fk-esr-info/infographic.html) but saying "INFOGRAPHIC"(instead of "HOME"):
![image](https://user-images.githubusercontent.com/2837257/110552017-6ed42980-80eb-11eb-81d4-07cd0b0879d9.png)
3. Ask Kelly / Seann if they want anything different from above, such as:
    1. Should we use "CONCEPTUAL MODEL" or different instead of "INFOGRAPHIC"?
    2. **Menu** direct navigation option throughout all web pages?
    3. **Banner** image?
    4. **Footer** ok?

**Comment by superjai** [comment]
[Infographic.html](https://marinebon.org/fk-esr-info/infographic.html) now works. 

Importantly, I included another version of this file ([infographic_model.html](https://github.com/marinebon/fk-esr-info/blob/main/infographic_model.html). The difference between these two versions is that infographic.html includes all of the extra css/javascript/html needed to make the page match with the existing fk-esr-info theme. Infographic_model contains just the minimum css/javascript to make the infographic work. This second version will be important for drupal translation and for translation to whatever other formats will be coming.

Please note the header continues to say "Home", not "Infographic". That's because, in the existing theme, the upper left always says Home. 

An email just went out to Kelly et al asking for their feedback.

**Comment by bbest** [comment]
Hi @superjai,

The hover works, but not getting any modals to show by clicking either icon or link in ToC. Looks like we need to included JQuery:

![image](https://user-images.githubusercontent.com/2837257/111364954-2074dc80-864f-11eb-8fbe-0ddc81108e67.png)

I recommend using:

```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
```

**Comment by superjai** [comment]
Fixed. The jquery library was there, but it wasn't included in the right order. With a library rearrange, it now works fine.

**Comment by bbest** [comment]
Huzzah @superjai! 🥳
