### ISSUE TITLE
librarian::shelf() issue -- Error in lib_paths()... paths are not writable

### ISSUE THREAD

**Issue by bbest** [marinebon/fk-esr-info#16]
@superjai  is getting this error on Windows (@bbest is not on Mac/Linux) when running [`_make_infographic_modals.R`](https://github.com/marinebon/fk-esr-info/blob/main/_make_infographic_modals.R):

```
Error in lib_paths(lib, make_path = TRUE, ask = ask) : 
  The paths

  '-1'

  are not writeable.
```

after attempting to run:

```r
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
shelf(
  dplyr, glue, highcharter, knitr, purrr, readr, rmarkdown, stringr, tibble, tidyr)
```

This is a well known error with `librarian` described here: https://github.com/DesiQuintans/librarian/issues/21.

**Comment by bbest** [comment]
The workaround seems to be installing the Github version a la:

```r
# Github version
remotes::install_github("DesiQuintans/librarian")

# CRAN version
#install.packages("librarian")
```

**Comment by superjai** [comment]
This worked for me.
