### ISSUE TITLE
accordion panel won't close in drupal

### ISSUE THREAD

**Issue by superjai** [marinebon/fk-esr-info#19]
hey @bbest - one small problem with the accordion implementation on the [drupal test page](https://www.integratedecosystemassessment.noaa.gov/node/756).  The accordion panels open fine, but they won't close.

Here's a screenshot of the console:

![errors](https://user-images.githubusercontent.com/1744300/112533514-684ae080-8d80-11eb-87d7-4e484f223df5.png)

For one, the jQuery Easy Tabs plugin isn't behaving properly - unsure if that is causing the problem.

**Comment by superjai** [comment]
hey @bbest - I created [my own version](https://marinebon.org/fk-esr-info/drupal-test.html) of the [drupal test page](https://www.integratedecosystemassessment.noaa.gov/node/756) and the accordion functionality now works fine. The issue is that two javascript libraries are being double-called on the drupal test page (jquery.min.js and bootstrap.min.js). If those libraries are called once, then everything works great.

This is the list of html tags sent to Avi to produce the working infographiq functionality:
```
<!-- infographiq: layout -->
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-9">
        <div id = "svg"> </div>
      </div>
      <div class="col-md-3">
        <div class="panel-group" id="accordion" role="tablist"
aria-multiselectable="true"></div>
      </div>
    </div>
  </div>

  <!-- infographiq: css & js dependencies -->
  <link rel="stylesheet"
href="https://marinebon.org/fk-esr-info/assets/css/bootstrap.min.css">
  <link rel="stylesheet"
href="https://marinebon.org/fk-esr-info/assets/css/infographiq.css">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
rel="stylesheet"/>
  <script src='https://marinebon.org/fk-esr-info/assets/js/d3.v5.min.js'></script>
  <script src='https://marinebon.org/fk-esr-info/assets/js/infographiq.js'></script>

  <!-- infographiq: link_svg() -->
  <script>
    link_svg(
    svg='https://marinebon.org/fk-esr-info/assets/svg/FKIEA_Ecosystem.svg',
    csv='https://docs.google.com/spreadsheets/d/e/2PACX-1vSAROGVpYB58Zkr8P0iwJdTMRPNLZtJ07IyUn-dQ62C2HMuCEScyl8x7urCD7QbRXQYSIJwDn_wku9G/pub?gid=0&single=true&output=csv',
    debug=true);
  </script>
```

**Comment by bbest** [comment]
Fantastic investigative coding @superjai 🧐 🌟

**Comment by superjai** [comment]
Hey @bbest - the infographic is now displaying properly on [my test drupal site ](http://ranganathan.info/drupal/node/4)(no iframe this time). I now understand how to make this work in Drupal, meaning I can train NOAA folks how to make the infographic functionality work in Drupal. 

Additionally, this is a good test environment to ensure that future iterations of the infographiq javascript work in drupal. The last step is to install the actual iea theme in my test site and I have asked for that theme.

**Comment by superjai** [comment]
hey @bbest. So I got the IEA theme and installed it [on my test drupal site](http://ranganathan.info/drupal/node/4). The theme files are missing elements, so the layout is very messed up. But that doesn't matter, as the infographic functionality works and ensuring that functionality is the only purpose of the installation. I think that closes up this issue.
