### ISSUE TITLE
replace existing highcharts data embedded in html with new csvURL approach

### ISSUE THREAD

**Issue by bbest** [marinebon/fk-esr-info#2]
With the new data strategy, we're reading a single remote authoritative CSV to feed the modals, such as resident-population: [code](https://github.com/marinebon/fk-esr-info/blob/main/modals/resident-population.html#L15-L27), [web](https://marinebon.org/fk-esr-info/modals/resident-population.html):

![image](https://user-images.githubusercontent.com/2837257/106044613-d3d04480-6094-11eb-9d85-4379eb71e290.png)

This is accomplished across modals by running [_make_infographic_modals.R](https://github.com/marinebon/fk-esr-info/blob/main/_make_infographic_modals.Rhttp://_make_infographic_modals.R), renders each modal with parameters for `csv` and `title` using the [_infographic_modal_template.html](https://github.com/marinebon/fk-esr-info/blob/main/_infographic_modal_template.html), so the above example for resident-population looks like so:

```javascript
csv   = 'https://marinebon.org/fk-esr-info/data/fknms_esr_indicator_data/keys_resident_population.csv';
title = 'Resident population';
icon  = 'resident-population';

if (csv == "NA"){
  document.getElementById("container").innerHTML = "<em>No data</em> yet assigned to icon <b>" + icon + "</b>. This needs to be specified in this Google Sheet: <a href='https://docs.google.com/spreadsheets/d/1_o8HOiZ_35uajupEsw6xLSsneTBTeLh0bqvFQvMpBNY/edit#gid=0'>icons to data | fk-esr-info</a>."
} else {
  Highcharts.chart('container', {
    title: {
      text: title
    },
    data: {
      csvURL: csv,
      firstRowAsNames: false,
      startRow: 4
    }, 
    series: [{
      name: 'value' }]
  });
}
```

The next step is to swap out the embedded data in the existing web pages, like in [human-activities.html#L94-L224](https://github.com/marinebon/fk-esr-info/blob/main/human-activities.html#L94-L224) where the resident-population data is assigned as an array called `averages`  and loaded as `data: averages`. We want to use the new `data: { csvURL: csv, ...}` approach.

This could happen in stages:
1. Manually updating the code to use the `csvURL` approach with an embedded url.
2. Template the pages into a src/ folder, then do the parameterized substitution like we did for the modals.

----

Background. Here's the latest with FK ESR infographic:

- infographic, using R
  [marinebon.org/fk-esr-info/infographic_r.html](https://marinebon.org/fk-esr-info/infographic_r.html)

I was able to generate all the [modals](https://github.com/marinebon/fk-esr-info/tree/main/modals) (popup page with data graph) using:
- [icons to data](https://docs.google.com/spreadsheets/d/1_o8HOiZ_35uajupEsw6xLSsneTBTeLh0bqvFQvMpBNY/edit#gid=0)
  Google Sheet for matching icon to data
- [_make_infographic_modals.R](https://github.com/marinebon/fk-esr-info/blob/main/_make_infographic_modals.Rhttp://_make_infographic_modals.R)
  R script to generate modals

**Comment by bbest** [comment]
Perhaps structural changes needed:

* [data.csvURL | highcharts API Reference](https://api.highcharts.com/highcharts/data.csvURL)
* [Select single series from csvURL - Highcharts official support forum](https://www.highcharts.com/forum/viewtopic.php?t=43520)
* [structuring data from csvURL - Highcharts official support forum](https://www.highcharts.com/forum/viewtopic.php?t=42255)

**Comment by bbest** [comment]
@superjai almost finished except waiting to hear back from Kelly on SST to complete that page, per #9

**Comment by superjai** [comment]
SST completed
