### ISSUE TITLE
consider highcharts alternatives

### ISSUE THREAD

**Issue by bbest** [marinebon/fk-esr-info#22]
* echarts
  * [Apache ECharts](https://echarts.apache.org/en/index.html)
  * [Create Interactive Graphs with Echarts JavaScript Version 5 • echarts4r](https://echarts4r.john-coene.com/)
* Google Charts
  * [Introduction to googleVis](https://cran.r-project.org/web/packages/googleVis/vignettes/googleVis_intro.html)
  * [Spatial and spatio-temporal objects in google charts](https://cran.r-project.org/web/packages/spacetime/vignettes/stgvis.html)
  * [Chart Gallery  |  Charts  |  Google Developers](https://developers.google.com/chart/interactive/docs/gallery)

**Comment by superjai** [comment]
So, it looks like NOAA is already using Google Charts, so that would be the preferred way to go. 

Here is my [first test of a plot](https://marinebon.org/fk-esr-info/deleteme.html) with Google Charts, with data coming from[ this google sheet](https://docs.google.com/spreadsheets/d/16mm9dCmz0D4GgC9gOCzOV2NasG58Z2bYu7LPVnCgqYE/edit#gid=0).

**Comment by superjai** [comment]
hey @bbest. [Updated chart](https://noaa-iea.github.io/fk-esr-info/google_charts_example.html) using Google Charts. This is using the [red grouper data.](https://docs.google.com/spreadsheets/d/1K05MhN9jdfIU8k4URGVnR3np3BZF1BmYGtvILsL_qPU/edit#gid=949872079).
And here is a [simple, tutorial version](https://noaa-iea.github.io/fk-esr-info/template_modal.html) to be used for training NOAA folks. This chart is working off of this [test sheet](https://docs.google.com/spreadsheets/d/1kb9SPsioe0163b2_xICUp1sOvYGQtBmiLiSkEeW1u-Y/edit#gid=0).

TO DO:

- [x] Allow for plotting multiple lines
- [x] Two Y axes
- [x] wrap into fsk-er-info modal windows

-
