### ISSUE TITLE
finish matching icons to data

### ISSUE THREAD

**Issue by bbest** [marinebon/fk-esr-info#3]
Finish matching [icons to data](https://docs.google.com/spreadsheets/d/1_o8HOiZ_35uajupEsw6xLSsneTBTeLh0bqvFQvMpBNY/edit#gid=0) with approach outlined in #2. Kelly Montenero working on this.

**Comment by bbest** [comment]
@mspector13 rockin this!

**Comment by mspector13** [comment]
Everything should be in order now @bbest. I flagged on cell because the data represented in the workbook are housed on two spreadsheets. Otherwise, we should be good to go!
