### ISSUE TITLE
need to update Gsheets with column headers vs default: Year | value | Series2 | Series3 ...

### ISSUE THREAD

**Issue by bbest** [marinebon/fk-esr-info#5]
The legend in the charts shows Year | value | Series2 | Series3 ... depending on the number of columns in the data. Let's update the original Gsheets of data, each of which is navigable from [icons to data | fk-esr-info - Google Sheets](https://docs.google.com/spreadsheets/d/1_o8HOiZ_35uajupEsw6xLSsneTBTeLh0bqvFQvMpBNY/edit#gid=0), with actual column headers on the first row (no need to insert extra lines above).

Then will need to update: https://github.com/marinebon/fk-esr-info/blob/89a88954737a1b7638f3308d5909331b28909730/_infographic_modal_template.html#L26-L30

to:

```javascript
    data: {
      csvURL: csv,
     /* to defaults below, so removable */
      firstRowAsNames: true,
      startRow: 0
    }, 
```

* 3 columns: [registered-vessels](https://marinebon.org/fk-esr-info/modals/registered-vessels.html)
  ![image](https://user-images.githubusercontent.com/2837257/106315034-7e746e80-621f-11eb-8ed3-c086f5c60d7e.png)

* 2 columns: [calcification](https://marinebon.org/fk-esr-info/modals/calcification.html)
  ![image](https://user-images.githubusercontent.com/2837257/106315080-8fbd7b00-621f-11eb-97e3-580dc13f0e49.png)

* 1 column: [beach-closures](https://marinebon.org/fk-esr-info/modals/beach-closures.html)
  ![image](https://user-images.githubusercontent.com/2837257/106315105-9d730080-621f-11eb-8bdc-7140ca4767f9.png)

**Comment by bbest** [comment]
Yay, working with latest commit on the first few:

* 3 columns: [registered-vessels](https://marinebon.org/fk-esr-info/modals/registered-vessels.html)
  ![image](https://user-images.githubusercontent.com/2837257/106316580-d6ac7000-6221-11eb-863b-fdc1c1806ba7.png)

* 2 columns: [calcification](https://marinebon.org/fk-esr-info/modals/calcification.html)
  ![image](https://user-images.githubusercontent.com/2837257/106316645-eaf06d00-6221-11eb-9ee5-9bcf6f497bc8.png)

* 1 column: [beach-closures](https://marinebon.org/fk-esr-info/modals/beach-closures.html)
  ![image](https://user-images.githubusercontent.com/2837257/106316684-f93e8900-6221-11eb-917e-1e9615a50544.png)

* 1 column: [black-grouper](https://marinebon.org/fk-esr-info/modals/black-grouper.html)
  ![image](https://user-images.githubusercontent.com/2837257/106316758-16735780-6222-11eb-82c4-f3687c32cd3c.png)

**Comment by bbest** [comment]
So @mspector13, after updating the Gsheets of data, feel free to run [_make_infographic_modals.R](https://github.com/marinebon/fk-esr-info/blob/main/_make_infographic_modals.R) to update the rest

**Comment by mspector13** [comment]
Done! Should be working now
