### ISSUE TITLE
headers in toc

### ISSUE THREAD

**Issue by bbest** [marinebon/fk-esr-info#6]
Hi @superjai,

We'd like to separate elements in the Table of Contents (toc) with headers using the `section` column in [icons to data | fk-esr-info - Google Sheets](https://docs.google.com/spreadsheets/d/1_o8HOiZ_35uajupEsw6xLSsneTBTeLh0bqvFQvMpBNY/edit#gid=0). This could take the following form (bolded section, bulleted list within):

**Ecosystem services**
- housing-disruption
- lobster
- recreational-fishing
- tourism-value 

**Habitat**
- calcification
- coral-living-tissue
- coral-species-richness
- macroalgae
- mangroves
- seagrass
- sponges-soft-corals 

**Human activities**
- commercial-fishing
- registered-vessels
- resident-population
- stonecrab
- tourism-population
- wastewater-treatment 

**Living resources**
- black-grouper
- brain-corals
- hogfish
- lionfish
- red-grouper
- reef-builders
- reef-fish-diversity
- yellowtail 

**Maritime heritage**
- maritime-hermitage
- stewardship 

**Sanctuary waters**
- beach-closures
- chlorophyll
- chlorophyll-a
- DIN
- DIP
- DO
- SST 

**NA**
- harmful-algal-blooms
- phytoplankton-taxonomy

Note that the **NA** icons need to get assigned a `section`. Here's how I generated the markdown list in R:

```r
icons_to_data %>% 
  arrange(section, icon) %>% 
  group_by(section) %>% 
  summarize(
    md_bullets = paste(icon, collapse = "\n- ")) %>% 
  mutate(
    md = glue("\n{section}\n- {md_bullets}", .trim = F)) %>% 
  pull(md) %>% 
  cat()
```

Hopefully you can implement this within [infographiq.js](https://github.com/marinebon/fk-esr-info/blob/main/assets/js/infographiq.js) as an extra argument to `link_svg()` like `toc_header_column`.

It would also be helpful to add an argument like `toc_header_colors` to define the background text colors to these sections as a named array `{section: color}` like:

```js
link_svg(
  toc_header_colors = {
    "Ecosystem services": #a8a832, 
    "Habitat": #32a852,
    ... };
```

These colors might relate to shading in the tryptic a la our notes in [FKIEA clickable infographic meetings - Google Docs](https://docs.google.com/document/d/1WcFMwmjjNV1ne2ejlWXGiv0HO44-safsXuEL_d9RFCs/edit#heading=h.a29zjo786ite).

**Comment by bbest** [comment]
Hi @superjai,

Other issues are looking close to completion.

Hopefully you'll have time to take a look at this "headers in toc" issue #6 before we meet today 2pm PT.

Then we can try pair programming to move it further forward.

**Comment by superjai** [comment]
hey @bbest - I am having trouble with the simplest thing that is causing my table of contents code to get stuck. I have created a test version of the page to illustrate my problem. Simply put, I am having trouble with updating variables within a nested function. The reason this comes up is that, for the creation of the table of contents, I had first planned to hold the section headers and titles within a two dimensional array. The only trouble is that I can't properly update that array within a nested function.

Okay, so my example is [test_infographic.rmd](https://github.com/marinebon/fk-esr-info/blob/main/test_infographic_r.Rmd) which is running the javascript file [testversion.js](https://github.com/marinebon/fk-esr-info/blob/main/assets/js/testversion.js). This is just your infographic.rmd file with a stripped down version of your original javascript code. 

In test_infographic.rmd I define two variables. This isn't the right place to define them, but for this example I at least know for sure that this makes them global variables.  section_list is an array for holding section and title names, while a_number is just that.

```
<script> 
var section_list = [,]; 
var a_number = 65; 
</script>
```

In the javascript, in the section of going through every line of the csv, I included the following two lines to update my two new variables:

```
        section_list.push([d.section, d.title]); 
        a_number = 5;
```

At the end of the javascript, I output the values of these variables using the console log:
![Screen Shot 2021-03-01 at 7 24 53 AM](https://user-images.githubusercontent.com/1744300/109518659-4bf8a400-7a5f-11eb-8014-0b6adc67cea0.png)

You'll notice that, though section_header has the right values in it, it initially shows up as empty. If I ask for a specific row of section_header, it definitely comes up empty. And the value for a_number is the initial one, not the changed one.

So I am sure that I am doing something silly here, but I just can't figure out what.

**Comment by bbest** [comment]
Hi @superjai,

The table of contents (toc) works now with commits above into [infographiq.js](https://github.com/marinebon/fk-esr-info/commit/fce6fe4aab203609e67733e3c83b89d8249cc033#diff-d030a672ca3e3c5d289edc79f0761f59a273bbe8336425c33e9d017d292ff0df) 🥳 

https://marinebon.org/fk-esr-info/infographic_r.html

![image](https://user-images.githubusercontent.com/2837257/109595099-b7c32700-7ac8-11eb-908d-5754c92b4014.png)

The only aspect that is not working yet is the sorting of secondary field per [comment](https://github.com/marinebon/fk-esr-info/commit/fce6fe4aab203609e67733e3c83b89d8249cc033#r47722273).

**Comment by superjai** [comment]
hey @bbest - here is a quick and dirty fix to remove the bullets in the list. I just added an inline css element to [infographic_r.rmd](https://github.com/marinebon/fk-esr-info/blob/15a777a51d20962e6af49915090c504593a8a9e8/infographic_r.Rmd#L33).

```
  <ul id = "svg_list" style="list-style-type: none;"></ul>
```

![Screen Shot 2021-03-02 at 3 06 37 PM](https://user-images.githubusercontent.com/1744300/109727287-ebee2480-7b68-11eb-9685-437e68b6dcf9.png)

Good enough or keep going on this?

**Comment by bbest** [comment]
Excellent @superjai! That looks good to me and is a more elegant solution than denesting those lists (since d3 JS likes to keep things nested).

The only other thing might be to dedent (opposite of indent) the child bullets, but all styling aspects would be best handled in the overall CSS referenced by a special class ("infotoc"?) in the parent list of this toc. 

I'm closing this issue. The above CSS suggestion might as well be handled in the context of your next CSS challenge, if you so choose to accept it, in #11.
