### ISSUE TITLE
get max(year) from csvURL using JS 

### ISSUE THREAD

**Issue by bbest** [marinebon/fk-esr-info#7]
Look forward to seeing this @superjai :)

**Comment by bbest** [comment]
Yay, using [assets/js/highcharts_wrapper.js](https://github.com/marinebon/fk-esr-info/blob/main/assets/js/highcharts_wrapper.js) so far in 

[human-activities.html#L134-L139](https://github.com/marinebon/fk-esr-info/blob/main/human-activities.html#L134-L139):

```r
    createGraph(
      theData = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRE4yLL8XRMi2BAUTMgL5hNxVJ-RwFy_kbnaPKEhllULeSdgfXPfSwvKGVjw8QDNqY3iOVHx6D9sgl5/pub?output=csv', 
      graph_location = "chart1", 
      title = "Keys Resident Population", 
      y_axis_label = "Population"
    );
```

**Comment by bbest** [comment]
Yay, sorted  with new createGraph()

**Comment by superjai** [comment]
More on that function createGraph(). I created a wrapper function for HighCharts that automatically calculates the bounds of the last five year purple band based on the data (like the image below):
![Screen Shot 2021-02-23 at 3 31 48 PM](https://user-images.githubusercontent.com/1744300/108922663-4bd64f80-75ec-11eb-9887-c32432bd0d1f.png)

This function is contained within a javascript file that I created called highcharts_wrapper.js, which is located in the [assets/js folder](https://github.com/marinebon/fk-esr-info/blob/main/assets/js/highcharts_wrapper.js).
